---
openapi: 3.1.0
components:
  schemas:
    GuitarDto:
      type: object
      required:
      - name
      - type
      properties:
        guitarId:
          $ref: "#/components/schemas/UUID"
        name:
          type: string
          pattern: \S
        type:
          $ref: "#/components/schemas/TYPE"
          type: string
          pattern: \S
        priceInUSD:
          type: number
          format: double
          minimum: 0
        stock:
          type: integer
          format: int32
          minimum: 0
    LinksDto:
      type: object
      properties:
        self:
          type: string
        first:
          type: string
        prev:
          type: string
        next:
          type: string
        last:
          type: string
    OffsetDateTime:
      type: string
      format: date-time
      examples:
      - 2022-03-10T12:15:50-04:00
    OrderRequestDto:
      type: object
      required:
      - guitarIds
      properties:
        orderId:
          $ref: "#/components/schemas/UUID"
        guitarIds:
          type: array
          minItems: 1
          items:
            type: string
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
        discountRequestedInUSD:
          type: number
          format: double
        createdAt:
          $ref: "#/components/schemas/OffsetDateTime"
    PageableGuitarDto:
      type: object
      properties:
        guitars:
          type: array
          items:
            $ref: "#/components/schemas/GuitarDto"
        links:
          $ref: "#/components/schemas/LinksDto"
    Quote:
      type: object
      properties:
        quoteId:
          $ref: "#/components/schemas/UUID"
        orderId:
          $ref: "#/components/schemas/UUID"
        discountInUSD:
          type: number
          format: double
        totalPriceWithDiscountInUSD:
          type: number
          format: double
        createdAt:
          $ref: "#/components/schemas/OffsetDateTime"
    QuoteDto:
      type: object
      properties:
        quoteId:
          $ref: "#/components/schemas/UUID"
        orderId:
          $ref: "#/components/schemas/UUID"
        discountInUSD:
          type: number
          format: double
        totalPriceWithDiscountInUSD:
          type: number
          format: double
        createdAt:
          $ref: "#/components/schemas/OffsetDateTime"
    TYPE:
      type: string
      enum:
      - ELECTRIC
      - CLASSIC
      - FOLK
      - GIPSY
      - JAZZ
    UUID:
      type: string
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
paths:
  /guitars:
    get:
      summary: Gets all guitars
      operationId: retrieveAllGuitars
      responses:
        "200":
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GuitarDto"
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
    post:
      summary: Creates a guitar
      operationId: createGuitar
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuitarDto"
        required: true
      responses:
        "201":
          description: Guitar creation successful
        "400":
          description: 'The request is invalid '
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
  /guitars/pages:
    get:
      summary: Gets all guitars and paginate the results
      operationId: findAllGuitarsWithPagination
      parameters:
      - name: pageNumber
        in: query
        schema:
          type: integer
          format: int32
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: 'Success '
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageableGuitarDto"
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
  /guitars/{guitarId}:
    put:
      summary: Updates a guitar
      operationId: updateGuitar
      parameters:
      - name: guitarId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GuitarDto"
        required: true
      responses:
        "200":
          description: 'Guitar update successful '
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuitarDto"
        "400":
          description: 'The request is invalid '
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
    get:
      summary: Gets a guitar
      operationId: getGuitar
      parameters:
      - name: guitarId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: 'Guitar update successful '
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GuitarDto"
        "400":
          description: 'The request is invalid '
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
    delete:
      summary: Deletes a guitar
      operationId: deleteGuitar
      parameters:
      - name: guitarId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: 'Guitar update successful '
        "400":
          description: 'The request is invalid '
        "500":
          description: Server unavailable
      tags:
      - Guitar Resource
  /orders-requests:
    get:
      summary: Gets all orders
      operationId: getAllOrders
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderRequestDto"
        "500":
          description: Server unavailable
      tags:
      - Order Request Resource
    post:
      summary: Creates an order
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequestDto"
        required: true
      responses:
        "201":
          description: Order creation successful
        "400":
          description: The request is invalid (probably the guitars IDs)
        "500":
          description: Server unavailable
      tags:
      - Order Request Resource
  /orders-requests/{orderId}:
    get:
      summary: Gets an order
      operationId: getOrder
      parameters:
      - name: orderId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderRequestDto"
        "400":
          description: The request is invalid (probably the guitars IDs)
        "500":
          description: Server unavailable
      tags:
      - Order Request Resource
  /quotes:
    get:
      summary: Gets all quotes
      operationId: findAll
      responses:
        "200":
          description: 'Success '
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
        "500":
          description: Server unavailable
      tags:
      - Quote Resource
    post:
      summary: Creates a quote
      operationId: createQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuoteDto"
        required: true
      responses:
        "201":
          description: 'Success '
        "400":
          description: 'Request invalid '
        "500":
          description: Server unavailable
      tags:
      - Quote Resource
info:
  title: Guitar Heaven API
  version: 1.0.1
  description: "Your guitar is probably here, check it out!"
  termsOfService: Free to use
  contact:
    name: Alexandre Touret
    email: techsupport@example.com
    url: https://blog.touret.info/contact/
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
