openapi: 3.0.0
info:
  title: Browse API
  description: >
    The Browse API has the following resources:
    - **item_summary**: Allows shoppers to search for specific items by keyword, GTIN, category, charity, product, image, or item aspects and refine the results using filters.
    - **item**: Allows shoppers to retrieve the details of a specific item or all items in an item group and check product compatibility.
  contact:
    name: eBay Inc
  license:
    name: eBay API License Agreement
    url: https://developer.ebay.com/join/api-license-agreement
  version: v1.19.9
servers:
  - url: https://api.ebay.com{basePath}
    description: Production
    variables:
      basePath:
        default: /buy/browse/v1
paths:
  /item_summary/search:
    get:
      tags:
        - item_summary
      description: >
        This method searches for eBay items by various query parameters and retrieves summaries of the items. 
        You can search by keyword, category, eBay product ID (ePID), or GTIN, charity ID, or a combination of these.
        Note: Only listings with `FIXED_PRICE` (Buy It Now) are returned by default.
      operationId: search
      parameters:
        - name: q
          in: query
          description: >
            A string consisting of one or more keywords used to search for items on eBay.
            Note: The `*` wildcard character is not allowed.
          required: false
          schema:
            type: string
          examples:
            example1:
              summary: Single keyword
              value: Fender Stratocaster
            example2:
              summary: Multiple keywords
              value: Gibson ES 335
        - name: X-EBAY-C-ENDUSERCTX
          in: header
          description: >
            This header supports revenue sharing for eBay Partner Network and improves accuracy of shipping and delivery estimates.
          required: false
          schema:
            type: string
          examples:
            example1:
              summary: End user context
              value: contextualLocation=country%3DUS%2Czip%3D10001
        - name: X-EBAY-C-MARKETPLACE-ID
          in: header
          description: >
            Identifies the seller's eBay marketplace. Required for marketplaces outside the US.
          required: false
          schema:
            type: string
          examples:
            example1:
              summary: US marketplace
              value: EBAY_US
        - name: Accept-Language
          in: header
          description: >
            Indicates the natural language and locale preferred by the user for the response.
          required: false
          schema:
            type: string
          examples:
            example1:
              summary: French language
              value: fr-FR
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPagedCollection'
              examples:
                example1:
                  summary: Example response for Fender Stratocaster
                  value:
                    href: "https://api.ebay.com/buy/browse/v1/item_summary/search?q=Fender+Stratocaster&limit=2"
                    total: 1000
                    limit: 2
                    offset: 0
                    itemSummaries:
                      - itemId: "v1|110298597847|0"
                        title: "Fender Stratocaster Electric Guitar - Black"
                        price:
                          value: 999.99
                          currency: USD
                        image:
                          imageUrl: "https://i.ebayimg.com/images/g/1yMAAOSwHjRe~Wf9/s-l1600.jpg"
                      - itemId: "v1|110298598973|0"
                        title: "Gibson Les Paul Standard Electric Guitar - Sunburst"
                        price:
                          value: 1500.00
                          currency: USD
                        image:
                          imageUrl: "https://i.ebayimg.com/images/g/2yMAAOSwHjRe~WgA/s-l1600.jpg"
                example2:
                  summary: Example response for Gibson ES 335
                  value:
                    href: "https://api.ebay.com/buy/browse/v1/item_summary/search?q=Gibson+ES+335&limit=2"
                    total: 0
                    limit: 2
                    offset: 0
                    itemSummaries: []

components:
  schemas:
    SearchPagedCollection:
      type: object
      properties:
        href:
          type: string
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        itemSummaries:
          type: array
          items:
            $ref: '#/components/schemas/ItemSummary'
    ItemSummary:
      type: object
      properties:
        itemId:
          type: string
        title:
          type: string
        price:
          $ref: '#/components/schemas/Price'
        image:
          $ref: '#/components/schemas/Image'
    Price:
      type: object
      properties:
        value:
          type: number
        currency:
          type: string
    Image:
      type: object
      properties:
        imageUrl:
          type: string
securitySchemes:
  api_auth:
    type: oauth2
    flows:
      clientCredentials:
        tokenUrl: https://api.ebay.com/identity/v1/oauth2/token
        scopes:
          https://api.ebay.com/oauth/api_scope: eBay OAuth scope
