-- This file allow to write SQL commands that will be emitted in test and dev.
-- The commands are commented as their support depends of the database
-- insert into myentity (id, field) values(1, 'field-1');
-- insert into myentity (id, field) values(2, 'field-2');
-- insert into myentity (id, field) values(3, 'field-3');
-- alter sequence myentity_seq restart with 4;


INSERT INTO Guitar (id, name, type, price, stock) VALUES (1, 'ES 335', 'ELECTRIC', 2500, 10);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (2, 'Stratocaster', 'ELECTRIC', 1500, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (3, 'Les Paul', 'ELECTRIC', 3000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (4, 'Yamaha C40', 'CLASSIC', 100, 20);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (5, 'Martin D-28', 'FOLK', 3500, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (6, 'Selmer Maccaferri', 'GIPSY', 4500, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (7, 'Gibson SG', 'ELECTRIC', 2000, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (8, 'Ibanez RG', 'ELECTRIC', 1100, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (9, 'Fender Telecaster', 'ELECTRIC', 1800, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (10, 'Gibson J-45', 'FOLK', 3200, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (11, 'Taylor 314ce', 'FOLK', 2100, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (12, 'Takamine GD20-NS', 'FOLK', 500, 15);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (13, 'Cordoba C5', 'CLASSIC', 300, 10);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (14, 'Flamenco Negra', 'CLASSIC', 1500, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (15, 'Gibson L-5', 'JAZZ', 7000, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (16, 'PRS Custom 24', 'ELECTRIC', 4000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (17, 'Jackson Soloist', 'ELECTRIC', 1800, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (18, 'Epiphone Dot', 'ELECTRIC', 800, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (19, 'Yamaha Pacifica', 'ELECTRIC', 600, 12);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (20, 'Gretsch White Falcon', 'ELECTRIC', 6000, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (21, 'Rickenbacker 330', 'ELECTRIC', 2200, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (22, 'Washburn HB35', 'ELECTRIC', 700, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (23, 'Gibson Hummingbird', 'FOLK', 3200, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (24, 'Seagull S6', 'FOLK', 400, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (25, 'Ovation Celebrity', 'FOLK', 800, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (26, 'Guild D-55', 'FOLK', 3500, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (27, 'Breedlove Oregon', 'FOLK', 2300, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (28, 'Godin Multiac', 'CLASSIC', 1200, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (29, 'Alhambra 5P', 'CLASSIC', 700, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (30, 'Kremona Fiesta', 'CLASSIC', 900, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (31, 'Ramirez 1a', 'CLASSIC', 8000, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (32, 'Takamine TC132SC', 'CLASSIC', 1400, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (33, 'ESP Eclipse', 'ELECTRIC', 2500, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (34, 'Charvel Pro-Mod', 'ELECTRIC', 1200, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (35, 'Dean ML', 'ELECTRIC', 900, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (36, 'Music Man JP15', 'ELECTRIC', 3500, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (37, 'Schecter Hellraiser', 'ELECTRIC', 1000, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (38, 'Gibson Firebird', 'ELECTRIC', 2300, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (39, 'Fender Mustang', 'ELECTRIC', 1000, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (40, 'Squier Classic Vibe', 'ELECTRIC', 400, 10);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (41, 'Epiphone Les Paul', 'ELECTRIC', 600, 9);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (42, 'Fender Jazzmaster', 'ELECTRIC', 1600, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (43, 'PRS SE Custom 24', 'ELECTRIC', 800, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (44, 'Ibanez JEM', 'ELECTRIC', 2800, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (45, 'Yamaha FG800', 'FOLK', 200, 20);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (46, 'Martin LX1E', 'FOLK', 500, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (47, 'Guild Starfire IV', 'ELECTRIC', 1600, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (48, 'Fender Duo-Sonic', 'ELECTRIC', 1000, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (49, 'Gibson ES-175', 'JAZZ', 4000, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (50, 'Ibanez Artcore', 'JAZZ', 600, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (51, 'Epiphone Casino', 'JAZZ', 900, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (52, 'Godin 5th Avenue', 'JAZZ', 1200, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (53, 'Yamaha A3R', 'FOLK', 800, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (54, 'Fender Malibu', 'FOLK', 700, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (55, 'Gibson J-200', 'FOLK', 4000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (56, 'Taylor GS Mini', 'FOLK', 600, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (57, 'Breedlove  Pursuit', 'FOLK', 900, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (58, 'Seagull Artist', 'FOLK', 1200, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (59, 'Cordoba Fusion', 'CLASSIC', 700, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (60, 'Kremona Verea', 'CLASSIC', 1000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (61, 'Ramirez R4', 'CLASSIC', 2000, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (62, 'Takamine GC5CE', 'CLASSIC', 600, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (63, 'Alhambra 7C', 'CLASSIC', 1300, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (64, 'Godin A6 Ultra', 'CLASSIC', 1500, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (65, 'Yamaha CG192S', 'CLASSIC', 800, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (66, 'Gibson ES-335', 'ELECTRIC', 3000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (67, 'ESP Horizon', 'ELECTRIC', 2700, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (68, 'Fender Lead II', 'ELECTRIC', 1200, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (69, 'Gretsch G2622', 'ELECTRIC', 700, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (70, 'Yamaha APX600', 'FOLK', 400, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (71, 'Taylor 210ce', 'FOLK', 1500, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (72, 'Gibson J-15', 'FOLK', 1700, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (73, 'Ibanez AW54CE', 'FOLK', 300, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (74, 'Breedlove Discovery', 'FOLK', 600, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (75, 'Seagull Maritime', 'FOLK', 1000, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (76, 'Cordoba C9', 'CLASSIC', 1300, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (77, 'Kremona Sofia', 'CLASSIC', 800, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (78, 'Ramirez R1', 'CLASSIC', 1500, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (79, 'Takamine P3FCN', 'CLASSIC', 1600, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (80, 'Alhambra 9P', 'CLASSIC', 1800, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (81, 'Gibson Firebird V', 'ELECTRIC', 2500, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (82, 'Fender Jag-Stang', 'ELECTRIC', 1300, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (83, 'Epiphone SG', 'ELECTRIC', 500, 10);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (84, 'Ibanez Talman', 'ELECTRIC', 700, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (85, 'Jackson Dinky', 'ELECTRIC', 1000, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (86, 'Dean Cadillac', 'ELECTRIC', 1200, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (87, 'PRS Santana', 'ELECTRIC', 3000, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (88, 'Music Man Silhouette', 'ELECTRIC', 2000, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (89, 'Gibson Explorer', 'ELECTRIC', 2200, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (90, 'Fender Coronado', 'ELECTRIC', 1600, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (91, 'Yamaha TRBX304', 'ELECTRIC', 350, 8);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (92, 'Gretsch G6120', 'ELECTRIC', 2900, 1);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (93, 'Ibanez SR505', 'ELECTRIC', 700, 6);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (94, 'Fender Bass VI', 'ELECTRIC', 1400, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (95, 'Gibson EB', 'ELECTRIC', 1200, 2);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (96, 'Fender Precision', 'ELECTRIC', 1500, 4);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (97, 'Music Man StingRay', 'ELECTRIC', 2000, 3);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (98, 'Epiphone Thunderbird', 'ELECTRIC', 500, 5);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (99, 'Yamaha BB434', 'ELECTRIC', 600, 7);
INSERT INTO Guitar (id, name, type, price, stock) VALUES (100, 'Gretsch G2220', 'ELECTRIC', 400, 6);

alter sequence Guitar_seq restart with 101;
